apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: alpine
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: alpine
    spec:
      containers:
      - image: techtrends:latest
        imagePullPolicy: IfNotPresent
        name: nginx-alpine
        ports:
          - containerPort: 31111
        resources:
           limits:
              cpu: 500m
              memory: 128mi
           requests:
              cpu: 250m
              memory: 64mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /healthz
            port: 3111
          failureThreshold: 30
          periodSeconds: 10 

